### PR TITLE
add support for empty response

### PR DESCRIPTION
**Pull request by ubogdan**
**Describe the PR**
Add support for "nil" type for the empty response

**Relation issue**
#941 

**Additional context**
NONE

### CODE REVIEW

**Review by sdghchj — APPROVED** [review]

**Review by sdghchj — APPROVED** [review]

**Comment by cristian-aldea** [comment]
Hello, I wanted to make a PR to document this features that was added.

Do I just need to update the README?
Do I need to update any other parts of this project to update this page? https://swaggo.github.io/swaggo.io/declarative_comments_format/api_operation.html

**Comment by ubogdan** [comment]
Technically all the features need to be updated in README.md and README_zh-CN.md. 
I'm ok if you update only the English version.

**Comment by cristian-aldea** [comment]
I'll see if I can update both.

Thanks, I'll send the PR sometime this weekend

**Comment by cristian-aldea** [comment]
There seems to be some discrepancy between the content for "Param Type" in https://swaggo.github.io/swaggo.io/declarative_comments_format/api_operation.html and in the README.md. Which is the source of truth?

Where does the content from https://swaggo.github.io/swaggo.io/ come from?

**Pull request merged**
