### PR TITLE
Implemented basic Tag support as API annotation

### PR DESCRIPTION
**Pull request by Nerzal**
**Describe the PR**
The parser can now also parse tag names and tag descriptions in general API info.

This produces these neat descriptions:
grafik

**Relation issue**
Issue #95 

**Additional context**
I have used "@@" as separator to be able to have both name & description in on line
Example: 
// @tag dogs @@ Dogs are cool
// @tag cats @@ Cats are cool

### CODE REVIEW

**Comment by easonlin404** [comment]
Thanks for your PR, I think it's better idea like following instead of using `@@` as separator :
```
// @tag.name dogs Dogs are cool
// @tag.description Dogs are cool
```

**Comment by easonlin404** [comment]
@Nerzal can you help to change?

**Comment by Nerzal** [comment]
Sure i can

**Comment by Nerzal** [comment]
I'll also add 

```
// @tag.docs.url
// @tag.docs.description
```

**Comment by Nerzal** [comment]
@easonlin404  fixed

**Comment by easonlin404** [comment]
@Nerzal Thanks four your contributions. 💯

**Pull request merged**
