### PR TITLE
feat: add extensions for params

### PR DESCRIPTION
**Pull request by Nightapes**
**Describe the PR**
Allow custom swagger fields in parameters

**Relation issue**
See: https://github.com/swaggo/swag/issues/445

### CODE REVIEW

**Comment by ubogdan** [comment]
Can you please fix the conflicts so we can have a coverage test running.

**Comment by Nightapes** [comment]
@ubogdan i fixed the PR

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@Nightapes Thanks for your contribution.

**Pull request merged**
