### PR TITLE
support for composition objects with pointers.

### PR DESCRIPTION
**Pull request by rubensayshi**
**Describe the PR**
this pull request adds support for embedded structs / composition with pointers.

```go
type Foo struct {
	Field1 string
}
type Bar struct {
	Field2 string
}

// this was working
type FooBarWorking struct {
	Foo
	Bar
}

// this was not working
type FooBarNotWorking struct {
	*Foo
	*Bar
}
```

### CODE REVIEW

**Comment by rubensayshi** [comment]
I don't understand why the go1.8 build is failing on travis ... it seems to fail on `make deps` o.O?

**Comment by asdptkt** [comment]
Welp, and I need this too.

**Comment by rubensayshi** [comment]
https://github.com/swaggo/swag/pull/228 tests fail because of this

**Comment by easonlin404** [comment]
@rubensayshi  Thanks for your contributions. 🎉

**Pull request merged**
