### PR TITLE
Add option language Portuguese in readme

### PR DESCRIPTION
**Pull request by Paulo-Lopes-Estevao**
**Describe the PR**
Add Portuguese language option in default readme

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]

**Comment by ubogdan** [comment]
@Paulo-Lopes-Estevao can you give us a hand with v2 Portuguese Readme?

**Comment by ubogdan** [comment]
Thanks for your contribution.

**Comment by Paulo-Lopes-Estevao** [comment]
> 

Yes I can.

**Comment by Paulo-Lopes-Estevao** [comment]
> @Paulo-Lopes-Estevao can you give us a hand with v2 Portuguese Readme?

Yes I can.

**Comment by ubogdan** [comment]
For now, I made a rebase from the master. Soon, we will update the en doc for v2. If you can keep the Portuguese
 in sync will be a great help for us.

Thanks!

**Comment by Paulo-Lopes-Estevao** [comment]
> For now, I made a rebase from the master. Soon, we will update the en doc for v2. If you can keep the Portuguese in sync will be a great help for us.
> 
> Thanks!

You are welcome, I will keep the language synchronized.

**Pull request merged**
