### PR TITLE
Added BearerAuth

### PR DESCRIPTION
**Pull request by sebastianbuechler**
**Describe the PR**
Added the bearer authentication method to security.

**Relation issue**
#804 

**Additional context**
API Doc
https://swagger.io/docs/specification/authentication/bearer-authentication/

### CODE REVIEW

**Comment by sebastianbuechler** [comment]
There is an external dependency required for this change, which will be tracked in PR https://github.com/go-openapi/spec/pull/122

**Comment by Nerzal** [comment]
@sebastianbuechler i fear that you'll run into a problem here. 
Isn't Bearer Auth part of Open API 3.0 Specification? 
The go-openapi spec lib currently does not support Open API 3.0 :/ 

I guess the correct way is just to use authentication
https://swagger.io/docs/specification/2-0/authentication/

**Comment by Nerzal** [comment]
More infos here: https://github.com/go-openapi/spec/issues/115

**Comment by zhasulan** [comment]
When swaggo/swag change go-openapi version? @Nerzal

**Comment by ubogdan** [comment]
@sebastianbuechler  I'm afraid this PR will simply be refused/closed due to the fact Barrer auth is not OAS2 compliant.

**Pull request closed without merging**
