### PR TITLE
chore: Remove gomonkey dependency from formatter

### PR DESCRIPTION
**Pull request by akojo**
**Describe the PR**
Refactor formatter file handling code so that formatter itself and the `fmt` command-line tool can be tested without using `gomonkey`.

Implement formatter tests so that they tests against actual pieces of go code with comments. While doing that clean up formatter code so that it's 100% covered by tests.

**Relation issue**
#1178

### CODE REVIEW

**Comment by akojo** [comment]
@ubogdan have you seen this one before with CI tests?

```sh
# cd .; git clone -- https://go.googlesource.com/lint /home/runner/work/swag/src/golang.org/x/lint
Cloning into '/home/runner/work/swag/src/golang.org/x/lint'...
fatal: unable to access 'https://go.googlesource.com/lint/': The requested URL returned error: 502
package golang.org/x/lint/golint: exit status 128
```

I couldn't reproduce locally

**Comment by ubogdan** [comment]
@akojo looks like a temporary issue.

**Comment by akojo** [comment]
Coverage test seems to be failing because decreasing the amount of code lines in the repo brings overall coverage down.

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@akojo Thanks for your contribution.

**Pull request merged**
