### PR TITLE
chore: alecthomas/template -> text/template

### PR DESCRIPTION
**Pull request by akojo**
**Describe the PR**

Since alecthomas/template is based on a severely outdated version (1.4)
of Go standard library, replace it with text/template in generated code.

Update example docs to match the change.

**Additional context**

Current code doesn't seem to be using newline elision anywhere. In case
that would be needed, `text/template` has supported it since Go 1.6.

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@easonlin404 any input here ?

**Comment by easonlin404** [comment]
LGTM I think `text/template` standard lib is more suitable if we want to get support and more stable.

**Review by easonlin404 — APPROVED** [review]

**Comment by ubogdan** [comment]
@akojo Thanks for your contributions.

**Comment by olliefr** [comment]
Closes issue #754, just saying 🙃

**Comment by olliefr** [comment]
@ubogdan hey, sorry to trouble you but do you guys have any time scale for the next version-tagged release, pretty please? 🙏 I'm very anxious to get rid of the `alecthomas/template` dependency in our project 😅

**Comment by christian-kreuzberger-dtx** [comment]
Same here!

**Comment by shepherdjerred** [comment]
Thanks for removing this dependency! This makes our lives a bit easier :)

**Comment by ubogdan** [comment]
You're wellcome.

**Pull request merged**
