### PR TITLE
debug info should go to stdout instead of stderr

### PR DESCRIPTION
**Pull request by ubogdan**
**Describe the PR**
add support to set up a logger for the parser. The default one should write to stdout instead of stderr.

**Relation issue**
#929 

**Additional context**
NONE

### CODE REVIEW

**Comment by ubogdan** [comment]
a CR will be much appreciated. 10x

**Comment by ubogdan** [comment]
@easonlin404 should we forget about this feature?

**Comment by ubogdan** [comment]
@sdghchj can you please give me a hand with a CR.

**Review by sdghchj — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
Thank you.

**Pull request merged**
