### PR TITLE
✍🏻 UPDATE(writeonly): add support for writeonly for schema prop types

### PR DESCRIPTION
**Pull request by en1tan**
**Describe the PR**
Support for writeonly tag concerning this issue https://github.com/swaggo/swag/issues/1139

**Additional context**
I submitted an issue for writeonly tag support for swaggo. Here is my proposed solution to it.
Hopefully I didn't make too much blunder as this is my first time contributing to Open Source.
Here is the link to the issue https://github.com/swaggo/swag/issues/1139.

### CODE REVIEW

**Comment by ubogdan** [comment]
@en1tan Unit tests are failing. I will start doing a Code Review only when all unit tests pass.

**Comment by en1tan** [comment]
alright

**Comment by ubogdan** [comment]
Please fix the conflict in `field_parser.go`, and I will do my best to review it.

**Comment by en1tan** [comment]
sure, will do that

**Comment by en1tan** [comment]
@ubogdan fixed

**Comment by ubogdan** [comment]
@en1tan  your PR doesn't pass unit tests.

**Comment by en1tan** [comment]
> @en1tan  your PR doesn't pass unit tests.

It's been sometime I checked the fork, will update and let you know

**Comment by en1tan** [comment]
@ubogdan I see the issue is with my request.
go-openapi does not have support for `writeOnly` neither does openapi 2.0

**Comment by ubogdan** [comment]
writeOnly is an OAS3-specific feature https://swagger.io/specification/#schema-object. Swag is currently supporting OAS 2.0

**Comment by en1tan** [comment]
yeah, I will close this PR now

**Pull request closed without merging**
