### PR TITLE
chore: release v1.8.0

### PR DESCRIPTION
**Pull request by rubensayshi**
Last release was in December, I think it would be good to do a new release.

Particularly the gin security release would be good to include since it fixes a CVE and some dependency management tools will flag this as an issue.

I was creating an issue to ask for a release, but figured by doing a PR if you agree then all you need to do is click the merge button, sorry if this comes over too aggressive just trying to make your life easier ;)

### CODE REVIEW

**Comment by rubensayshi** [comment]
how can this make the coverage go down o.O

**Comment by ubogdan** [comment]
@rubensayshi Unfortunately we can't jump to 1.8.0 just because of a security fix.

**Comment by ubogdan** [comment]
We just made a release for 1.7.1.

**Comment by rubensayshi** [comment]
:+1: thanks for the release

**Pull request closed without merging**
