### PR TITLE
Handle *ast.InterfaceType as any type (no type)

### PR DESCRIPTION
**Pull request by ViktorPegy**
**Describe the PR**
Allow defining models with interface{} type of fields

**Additional context**
Interface type meaning any type (or no type) in swagger terms: 
https://swagger.io/docs/specification/data-models/data-types/#any

If you ready to accept changes I'll write some tests for that

### CODE REVIEW

**Comment by rizalgowandy** [comment]
LGTM

**Comment by ubogdan** [comment]
@ViktorPegy is this related to any open issue? If yes, please edit the PR and add the reference. 
Unfortunately, I don't see the CI running the code tests so I can't tell you at this time if we can accept or refuse it. 

Kindly please do another commit in order to trigger the CI and I will try to take a look at it ASAP.

**Comment by rizalgowandy** [comment]
https://github.com/swaggo/swag/issues/850
https://github.com/swaggo/swag/issues/853

**Comment by ubogdan** [comment]
@rizalgowandy, the tests are failing on https://github.com/ViktorPegy/swag, and @ViktorPegy doesn't seem to be available to update the PR.

**Comment by rizalgowandy** [comment]
He has archived his repository.
Kinda need to recommit his code.
`This repository has been archived by the owner. It is now read-only.`

**Comment by matt-monacelli** [comment]
Is this PR going to be merged anytime soon?  I am having to update to go 1.17 and this issue is blocking me from doing so.  If not, I guess I will be forced to have incomplete docs.  Thanks!

**Comment by ubogdan** [comment]
Unfortunately, there is no way we can merge this PR due to its conflicts and missing CI results.

**Comment by matt-monacelli** [comment]
It looked pretty simple and straight forward, can it not be recreated?

On a side note, I was able to resolve my critical issue by adding the
"--parseDependency" option to my swag init call in our CI/CD script, but
would be nice to see this fixed.  Thanks for the reply!

**Comment by ubogdan** [comment]
Closing reason: Outdated.
An rework regarding this can be found here #988

**Comment by ubogdan** [comment]
The feature was implemented and will be released in v1.7.2.

**Pull request closed without merging**
