### PR TITLE
add support cross package

### PR DESCRIPTION
**Pull request by pei0804**
**Describe the PR**
I also made it possible to create a model in Cross package

**Relation issue**
close https://github.com/swaggo/swag/issues/159

**Additional context**
Very bad code, but it works.

### CODE REVIEW

**Comment by easonlin404** [comment]
@pei0804 can you provide an example about how to enable cross pkg?

**Comment by pei0804** [comment]
It's here.
https://github.com/swaggo/swag/blob/0a99c8c47b9d78dccaec2d4031d8978f08e5cff6/testdata/simple/web/handler.go#L64

**Comment by easonlin404** [comment]
IMO seems like can make code more concise, rest LGTM.

**Comment by pei0804** [comment]
I think so too.

**Comment by t-evers** [comment]
I can confirm cross-package works now. But I continue to run into the "not supported, but it will be set with string temporary when it comes to using models from another project.
Example layout as it resides in go/src:
our.domain/project1/models/somedata.go
our.domain/project2/models/otherdata.go

Now, if project2 has the REST API to be documented and the models in "otherdata.go" contain types declared in project1/somedata.go, I ran into that problem.

Can you confirm that and will that be fixed too?

**Comment by pei0804** [comment]
I want a fail code. Can you give?

**Comment by t-evers** [comment]
Of course. Here you go. 
Output of "swag init":
[example.zip](https://github.com/swaggo/swag/files/2235530/example.zip)
2018/07/27 13:02:55 Generate swagger docs....
2018/07/27 13:02:55 Generate general API Info
SomeData is not supported. but it will be set with string temporary. Please report any problems.2018/07/27 13:02:55 Generating api.ResponseObject
2018/07/27 13:02:55 create docs.go at  docs/docs.go

**Comment by pei0804** [comment]
thx. I'll check tommrow.

**Comment by pei0804** [comment]
I understood the problem.
swag is parsing directories under the location where init was executed.

```
our.domain/project1/models/somedata.go
our.domain/project2/models/otherdata.go
```

Project2 can't be analyzed because project 1 is'nt visible.
It seems that it is necessary to put project1 on project 2 or less now.

**Comment by pei0804** [comment]
@t-evers 
for you
https://github.com/swaggo/swag/pull/179#pullrequestreview-142388523

**Pull request merged**
