### PR TITLE
Add flag to generate documentation only for specifics tags

### PR DESCRIPTION
**Pull request by Trial97**
**Describe the PR**
Added CLI flag to generate the doc for them if specified.
It helps when you want to generate multiple pieces of documentation(e.g. one for devs and a separate one for customers)

**Relation issue**
None

**Additional context**
ToDo:
- [x] Add a flag to the parser
- [x] Add tests

### CODE REVIEW

**Comment by ubogdan** [comment]
@Trial97 Not sure about it.

**Comment by Trial97** [comment]
@ubogdan Feel free to close it if this is not desired :D.
But why not? Does this PR lack in some way or form?

**Comment by ubogdan** [comment]
@Trial97 I'll like to hear @sdghchj opinion.

**Comment by sdghchj** [comment]
@ubogdan 
I agree on this feature, for my team had also asked for it some days ago.
We usually need a piece of open API for customers and another piece for develpers in our own team.

**Review by ubogdan — APPROVED** [review]
LGTM

**Pull request merged**
