### PR TITLE
Add multipleOf field to parser.

### PR DESCRIPTION
**Pull request by jimmycannlfs**
Describe the PR
Add ability to specify multipleOf struct field

Relation issue
N/A

----
Sorry, ran into an issue and needed to reopen

### CODE REVIEW

**Comment by ubogdan** [comment]
Good job so far. We need a coverage test passing.

**Comment by jimmycannlfs** [comment]
Cool thanks! It's a little hard to tell, but that last commit should cover it :D

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
Thanks for your contribution.

**Pull request merged**
