### PR TITLE
issue-503: added type map in example value

### PR DESCRIPTION
**Pull request by Arrim**
**Describe the PR**
Add example tag for maps

**Relation issue**
https://github.com/swaggo/swag/issues/503

**Additional context**
Example:
 ```
type MyStruct struct {
    MyMap map[string]string 'json:"my_map" swaggertype:"map,string" example:"key1:value1,key2:value2"'
  }
```

### CODE REVIEW

**Comment by sdghchj** [comment]
1. Swagger have no real map or dictionary type, so it use object type with additionalProperties  alternatively. And also, schemaType have no chance to be "map" in your PR. You can test it.
2. I found swagger editor doesn't support example for object type. You can confirm it.

**Comment by Arrim** [comment]
@sdghchj  This type is needed to form an example json request with an arbitrary data set. For instance:
{
"data": {
"myKey1": "myData1",
"myKey2": "myData2",
"myKey3": "myData3",
}
}
I know that maybe this is a design error, but sometimes it is necessary. At the moment, swag is not able to generate such data.
And yes, I checked with my example - it works.

**Comment by sdghchj** [comment]
@Arrim I see, you set `map` schema type in tag `swaggertype`  for the original map or interface{} type, which does work actually.

**Comment by sdghchj** [comment]
@Arrim  Can you show your exmaple result?

**Comment by rogaha** [comment]
any updates here?

**Comment by Arrim** [comment]
Hi. Sorry for the delay. I updated my code.
Swagger really not support map type. But map type in go is an object in swagger(JSON). 
I use object type for a map and check child type in the "defineTypeOfExample" method. If child type not set returned error. And if the child typeset and correct, I add an example in documentation. 

I add an example code in the repository, where you may check the correct result.

**Comment by Arrim** [comment]
@sdghchj @easonlin404 Hi. You can merge pr?

**Review by sdghchj — APPROVED** [review]
LGTM

**Pull request merged**
