### PR TITLE
add array of standard types

### PR DESCRIPTION
**Pull request by nadilas**
cleanup array of structs method and add array of standard types (e.g. []string)

add fix TransToValidSchemeType(typeName string) to support user defined types in ast.Ident fields

### CODE REVIEW

**Comment by nadilas** [comment]
Found one additional line, which needs to be swapped:

`parser.go:294`:
```go
CheckSchemaType(schType)
```

should be:
```go
if len(arrType) == 0 {
	CheckSchemaType(schType)
} else {
       CheckSchemaType("array")
}
```

**Comment by easonlin404** [comment]
@nadilas can you help to fix testing?

```
--- FAIL: TestParseSimpleApi (0.02s)
```

**Comment by nadilas** [comment]
Yes, sorry I missed that.

**Comment by easonlin404** [comment]
@nadilas  LGTM. Thanks for all your contributions. 💯

**Pull request merged**
