### PR TITLE
feat: support struct field as required.

### PR DESCRIPTION
**Pull request by zhongkeqin**
**Describe the PR**
Support declare a parameter in struct as required [#123](https://github.com/swaggo/swag/issues/123)

### CODE REVIEW

**Comment by pei0804** [comment]
Can you fix travis error?
I do not check until become green.

**Comment by zhongkeqin** [comment]
ok，I will check it. But I don`t know where is the problem.

**Comment by pei0804** [comment]
https://travis-ci.org/swaggo/swag
Can you see it?

**Comment by zhongkeqin** [comment]
fixed travis error.

**Comment by pei0804** [comment]
LGTM

**Comment by peter-crist** [comment]
Why isn't there a required readme change with this PR? It is very difficult to find what struct tags swaggo supports due to this.

**Pull request merged**
