### PR TITLE
multi description support

### PR DESCRIPTION
**Pull request by elvizlai**
impl #139

multi description support, using `<br>` as spliter

### CODE REVIEW

**Comment by easonlin404** [comment]
Using `<br>` as spliter it not good approach, please read the next line if it's also a `@description`.

**Comment by elvizlai** [comment]
@easonlin404 I think checking has none empty previous is fine. reading next line may not work if:
```
// @Description hello1
// @Tags groupA
// @Description hello2
```

**Comment by elvizlai** [comment]
@easonlin404 can this be merged?

**Comment by easonlin404** [comment]
@pei0804 what's your thought on this?

**Comment by pei0804** [comment]
https://github.com/swaggo/swag/pull/219#issuecomment-426457416
If it already exists, can not you add it?

**Comment by easonlin404** [comment]
@elvizlai  After reviewed this change, LGTM. Can you help add tests for it?

**Comment by elvizlai** [comment]
@easonlin404 test case added, but oops, ci's golint itself failed. maybe re-run it later.

**Comment by elvizlai** [comment]
@easonlin404 can this be merged now?

**Comment by easonlin404** [comment]
Thanks for your contribution.

**Comment by lfaoro** [comment]
how do we use it in the end?
// @Description <br> new line
or
// @Description line 1
// @Description line 2?

**Comment by easonlin404** [comment]
@lfaoro please use:
```
// @description line 1
// @description line 2
```

**Comment by lfaoro** [comment]
@easonlin404 multiline doesn't work for me
I'm using `swag version v1.3.2` - I guess this change is not released yet

**Comment by lfaoro** [comment]
@easonlin404 actually I found the problem, there's a typo in the latest released tag `v.1.4.0` should be `v1.4.0` the extra dot there screws go mod up as it is not a valid semver tag.

**Comment by easonlin404** [comment]
@lfaoro ok, I will bump to the correct version, sorry for your inconvenience.

**Comment by lfaoro** [comment]
awesome, lemme try if `@description` works now for multiline

**Comment by lfaoro** [comment]
@easonlin404 multiple `@description` keys doesn't work in `v1.4.0` only using the <br> key on 1 @description element works for multiline

**Comment by kolaente** [comment]
I have the same issue: #276

**Pull request merged**
