### PR TITLE
Add command param for proprty naming strategy.

### PR DESCRIPTION
**Pull request by glassonion1**
## outline
- add command line param like snakecase
```
% swag init propertyStrategy snakecase
```
or 
```
% swag init -p snakecase
```

## test result
```
% go test -v ./gen                                                                                                                                                                     (git)-[snakecase] glassonion999@gmail.com
=== RUN   TestGen_Build
2018/05/09 16:46:22 Generate swagger docs....
2018/05/09 16:46:22 Generate general API Info
2018/05/09 16:46:22 Generating web.APIError
2018/05/09 16:46:22 Generating web.RevValue
2018/05/09 16:46:22 Generating web.Pet2
2018/05/09 16:46:22 Generating web.Tag
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Generating web.Pet
2018/05/09 16:46:22 Generating web.Tag
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Generating web.Pet
2018/05/09 16:46:22 create docs.go at  ../testdata/simple/docs/docs.go
--- PASS: TestGen_Build (0.01s)
=== RUN   TestGen_BuildSnakecase
2018/05/09 16:46:22 Generate swagger docs....
2018/05/09 16:46:22 Generate general API Info
2018/05/09 16:46:22 Generating web.APIError
2018/05/09 16:46:22 Generating web.RevValue
2018/05/09 16:46:22 Generating web.Pet2
2018/05/09 16:46:22 Generating web.Tag
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Generating web.Pet
2018/05/09 16:46:22 Generating web.Tag
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Skipping 'web.Pet2', already present.
2018/05/09 16:46:22 Generating web.Pet
2018/05/09 16:46:22 create docs.go at  ../testdata/simple2/docs/docs.go
--- PASS: TestGen_BuildSnakecase (0.00s)
PASS
```

### CODE REVIEW

**Comment by pei0804** [comment]
I prefer `swag init -p snakecase`

**Comment by easonlin404** [comment]
why we need snake case? I don't understand this feature of purpose. 😉 ?

**Comment by glassonion1** [comment]
The json tag may misspell. In my project, it automatically converts it to a snake case with the program at the timing of json.Marshal / Unmarshal.

**Comment by easonlin404** [comment]
@pei0804 please also help to review.

**Comment by pei0804** [comment]
In that case prepare a structure that does not write json tag for testing.

**Comment by glassonion1** [comment]
JSON should be a camel case as it is a format born from JavaScript.
However, in fact it is more common to make a snake case.
I think that it is better to output the default in the camel case.

**Comment by glassonion1** [comment]
> In that case prepare a structure that does not write json tag for testing.

“testdata/simple2” is no json tag structs.
Added unit test for parser.

**Comment by pei0804** [comment]
By the way, Currnet default format is uper camelcase.
I want to choice lower camelcase or upper camelcase.
If possible, I would like you to make it available for selection.

Thx PR.

**Comment by glassonion1** [comment]
Certainly, it is not good that the upper camel case is the default.
I am going to fix it so I will make another PR.

**Pull request merged**
