### PR TITLE
Add support for error field in model

### PR DESCRIPTION
**Pull request by lahsivjar**
**Describe the PR**
Add support for error type ina a field in a data model

**Relation issue**
https://github.com/swaggo/swag/issues/793

**Additional context**
 If error type is a field in a data model for request or response then it fails to parse with an error "cannot find type definition: error"

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
The output of json.Marshal for the `error` type is an empty object `{}`. 

```go
package main

import (
	"encoding/json"
	"errors"
	"fmt"
)

type Data struct {
	Name  string
	Age   int
	Error error
}

func main() {
	data := Data{
		Name:  "John",
		Error: errors.New("unable to parse user John"),
	}
	json, err := json.Marshal(data)
	if err != nil {
		panic(err)
	}
	fmt.Printf("json output: %s", json)
}
```

Output:
```
json output: {"Name":"John","Age":0,"Error":{}}
```

The `error` type is not a Primitive type is a private Interface type and the field should be skipped during struct parsing. 
 
@lahsivjar Please let me know if you are willing to update the PR according to the conclusion above.

Thanks,
Bogdan

**Review by ubogdan — CHANGES_REQUESTED** [review]
Error is a private interface, it shouldn't be marshaled to string. See comment above.

**Comment by lahsivjar** [comment]
@ubogdan A bit busy this week, will take a look and try to submit a PR next week.

**Comment by ubogdan** [comment]
@lahsivjar No worries. Take your time!

**Comment by ubogdan** [comment]
@lahsivjar any updates here?

**Comment by ubogdan** [comment]
@lahsivjar I will like to include this in the current release, unfortunately, it's not ready to be released.

**Comment by lahsivjar** [comment]
@ubogdan Have been away from the project which uses this for a long time. Looking at the above PR isn't what you expect just a revert of [this commit](https://github.com/swaggo/swag/pull/794/commits/de3d6b4f5acbecbec4c0fca8b38231794c348c02)?

**Comment by ubogdan** [comment]
Ok then, you can close the PR.

**Pull request closed without merging**
