### PR TITLE
Update dependencies and fix tests

### PR DESCRIPTION
**Pull request by akojo**
**Describe the PR**

Upgrade github.com/go-openapi/spec and golang.org/x/tools to latest
versions.

Upgrading github.com/go-openapi/spec v0.19.11 -> v.0.19.14 generates
empty "description" members for responses and empty "authorizationUrl"
members for securityDefinitions when they're missing. This causes tests
to fail. Fix by adding the missing empty definitions to expected test
results.

**Additional context**
Since travis-ci test builds always fetch deps and build before running tests,
they break because of the change in go-openapi/spec

### CODE REVIEW

**Comment by sdghchj** [comment]
I just can't figure out why it generates empty  members?

**Comment by akojo** [comment]
According to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) `description` and `authorizationUrl` are required fields in those contexts. Apparently that's the reason they are now always included

**Comment by sdghchj** [comment]
> According to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) `description` and `authorizationUrl` are required fields in those contexts. Apparently that's the reason they are now always included

So where is it that the member `description` is set required?

**Comment by akojo** [comment]
> So where is it that the member `description` is set required, I mean in source code?

[Here's](https://github.com/go-openapi/spec/commit/119312bce69c7a518c3382167495c53240bb7966) in spec the commit that always generates those two members. Apparently it's included in version 0.19.13 and onwards

**Comment by sdghchj** [comment]
> > So where is it that the member `description` is set required, I mean in source code?
> 
> [Here's](https://github.com/go-openapi/spec/commit/119312bce69c7a518c3382167495c53240bb7966) in spec the commit that always generates those two members. Apparently it's included in version 0.19.13 and onwards

OK I see.
But, as you memtioned that it's included in version 0.19.13,  however, I just upgrade it to v0.19.12, it still failed when running those tests.  Refer to [https://github.com/swaggo/swag/pull/836/checks?check_run_id=1422025199](https://github.com/swaggo/swag/pull/836/checks?check_run_id=1422025199)

**Review by sdghchj — APPROVED** [review]
LGTM

**Comment by sdghchj** [comment]
@akojo Thank you all the same.

**Pull request merged**
