### PR TITLE
refactor: remove dependency on gin

### PR DESCRIPTION
**Pull request by akojo**
**Describe the PR**
Since swag doesn't have a direct dependency on gin-gonic/gin, drop it as a dependency in the main module:
- Add go.mod into examples so that they can be used stand-alone and pull in correct deps
- Use `http` package for handlers instead of gin in tests
- Use `http` in `example/basic` since tests depend on in
- Clean up main go.mod

**Relation issue**
https://github.com/swaggo/swag/issues/796

### CODE REVIEW

**Comment by easonlin404** [comment]
@akojo could you help rebase master and fix conflicts?

**Comment by akojo** [comment]
> @akojo could you help rebase master and fix conflicts?

Ah, again master ran away :smiley: . Rebased.

**Comment by touyu** [comment]
Is this PR still working?

I'm using echo-swagger, but I'm having trouble with https://github.com/swaggo/gin-swagger/issues/128 because swag depends on gin-swagger.

**Comment by akojo** [comment]
Is there something I could help with to get this moving?

**Comment by ubogdan** [comment]
@akojo in order to review your PR we need to see CI tests passing.

**Comment by akojo** [comment]
Hmm, any idea why go1.13 tests fail? Running that specific test doesn't work on my fork since the paths don't match

**Comment by akojo** [comment]
Heh, silly me. Didn't realize that my changes to `examples/` broke the build

**Comment by ubogdan** [comment]
For some reason the coverage decreased with 0.25 and the checks are failing. 
@easonlin404 I can't merge the PR due to this issue.

**Comment by akojo** [comment]
:thinking: Looks like updating github.com/go-openapi/spec to v0.19.14 breaks the build by changing the formatting of output slightly

**Comment by akojo** [comment]
See #835

**Review by sdghchj — APPROVED** [review]
LGTM

**Comment by akojo** [comment]
That -0.13% coverage decrease seems to be bogus since parser test should never hit the line in question in the first place. Only duplicate `@ID` declaration in tests is in a POST annotation :thinking:

**Review by sdghchj — APPROVED** [review]
LGTM

**Pull request merged**
