### PR TITLE
Allow unsafe characters in param name

### PR DESCRIPTION
**Pull request by pindamonhangaba**
**Describe the PR**
Allow params to have unsafe chars in their name, ex.: 

    // @Param startedAt[gte] query string false "Filter started date"

### CODE REVIEW

**Comment by easonlin404** [comment]
@pindamonhangaba  can you help add tests?

**Comment by pindamonhangaba** [comment]
Something like this?

```
// Test ParseParamComment
func TestParseParamCommentByID(t *testing.T) {
	comment := `@Param unsafe_id[lte] query int true "Unsafe query param"`
	operation := NewOperation()
	err := operation.ParseComment(comment, nil)

	assert.NoError(t, err)
	b, _ := json.MarshalIndent(operation, "", "    ")
	expected := `{
    "parameters": [
        {
            "type": "integer",
            "description": "Unsafe query param",
            "name": "unsafe_id[lte]",
            "in": "query",
            "required": true
        }
    ]
}`
	assert.Equal(t, expected, string(b))
}
```

**Comment by easonlin404** [comment]
@pindamonhangaba yes

**Comment by easonlin404** [comment]
@pindamonhangaba Thanks for your contributions.

**Pull request merged**
