### PR TITLE
Support quotes and tabs in general API description

### PR DESCRIPTION
**Pull request by j0s**
**Describe the PR**
Handle quotes and tabs in general API description. The two-stage application of templates when generating `docs.go`, and then applying a template in [`ReadDoc()`](https://github.com/swaggo/swag/blob/940d07268e91254eb18c2978cda233381ab643cb/gen/gen.go#L283), resulted in escaping of quotation mark getting lost. This PR re-adds adds those quotations using a less than beautiful workaround, but at least it works on my test cases.
It also adds a test that compiles the generated file `docs.go`, runs the `ReadDoc()` method, and compares the output to a template.

**Related issue**
https://github.com/swaggo/swag/issues/738

**Additional context**
I stumbled upon this when expanding my documentation using markdown. When writing long descriptions, supporting quotation marks and tabs would be very useful.

### CODE REVIEW

**Comment by easonlin404** [comment]
@j0s sorry, because ci check had some issue there before. could you help retry the build again? eg: some minor changes

**Comment by j0s** [comment]
Ok, so I fixed a linting error. But the coverage must be caused by codecov not being run for a while right? It's complaining that coverage of `parser.go` has decreased, but I haven't touched that file?

**Comment by j0s** [comment]
Is there anything blocking this from being merged, except for the travis job that does not seem to run?

**Comment by j0s** [comment]
I would still like this to be merged if it looks good to you.

**Comment by jecolasurdo** [comment]
Any movement on this?

**Review by sdghchj — APPROVED** [review]

**Pull request merged**
