### PR TITLE
Add support for x-tokenname in oauth2 specs

### PR DESCRIPTION
**Pull request by lahsivjar**
Signed-off-by: lahsivjar <lahsivjar@gmail.com>

**Describe the PR**
Add support for x-tokenname in oauth2 specs

**Relation issue**
https://github.com/swaggo/swag/issues/790

**Additional context**
 Allow swag to parse "x-tokenname" variable from the GeneralAPI annotations and apply it to oauth2 specs so that we can select another JSON field (default is "access_token") in the token response from a OAuth2.0 server

### CODE REVIEW

**Comment by lahsivjar** [comment]
@easonlin404 @sdghchj @pei0804 Can you help to review this?

**Comment by lahsivjar** [comment]
@easonlin404 @sdghchj @pei0804 Friendly ping

**Review by sdghchj — APPROVED** [review]
LGTM

**Review by easonlin404 — APPROVED** [review]
LGTM

**Pull request merged**
