### PR TITLE
Adding custom header

### PR DESCRIPTION
**Pull request by jayhuang75**
Adding the custom header in Param

### CODE REVIEW

**Comment by easonlin404** [comment]
@jayhuang75 Can you provide an example or document to demonstrate this PR?

**Comment by jayhuang75** [comment]
@easonlin404 Yes, definitely, here is the example
`// @Param   Authorization header string true "With the bearer started"
`

**Comment by easonlin404** [comment]
LGTM

**Comment by easonlin404** [comment]
@jayhuang75 please use the email address used for the commits is associated with your GitHub account next time. 😄   https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Pull request merged**
