### PR TITLE
Added support for @x- attributes on security definition

### PR DESCRIPTION
**Pull request by pmorelli92**
Relates to issue #970.

Before this PR the only `@x-` attribute supported on the security definition was the hardcoded `x-tokenName`. After this PR all the `@x-` attributes that are parsed in the same block than the security definition are going to be added.

Added extra logic for not adding twice the `@x-` attributes that are present on the security definition and removed the hardcoded case scenario for token name as well.

### CODE REVIEW

**Comment by pmorelli92** [comment]
@sdghchj @ubogdan  Hi guys! Sorry to bother you with the tag, but I would like to know if you can give some love to this PR. Unfortunately, at the company I am working, I have a deadline soon and I would need to know if I can use this dependency or not. Sorry again

**Comment by pmorelli92** [comment]
Done! @ubogdan

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@pmorelli92 Thanks for your contribution.

**Pull request merged**
