### PR TITLE
feat: add command for format the swag comment.

### PR DESCRIPTION
**Pull request by HYY-yu**
**Describe the PR**
Hello, Please see a example:
```
// GetStructArrayByString example
// @Description get struct array by ID
// @ID get-struct-array-by-string
// @Accept  json
// @Produce  json
// @Param   some_id     path    string     true        "Some ID"
// @Param   offset     query    int     true        "Offset"
// @Param   limit      query    int     true        "Offset"
// @Param   pet_id  query  int false "pet' id"
// @Param   book_id query int false "book' id"
// @Param   app_id query int false "app' id"
// @Param   x_key query string false "secret key"
// @Success 200 {string} string	"ok"
// @Failure 400 {object} web.APIError "We need ID!!"
// @Failure 404 {object} web.APIError "Can not find ID"
// @Router /testapi/get-struct-array-by-string/{some_id} [get]
```
As you can see, If I have a lot of params, The format of comment will look very messy. 

So, we can create a command like `gofmt`, It automatically formats the "swag" comments.
Like this: 
```shell
$ swag fmt -h
NAME:
   swag fmt - format swag comments

USAGE:
   swag fmt [command options] [arguments...]

OPTIONS:
   --dir value, -d value          Directories you want to parse,comma separated and general-info file must be in the first one (default: "./")
   --exclude value                Exclude directories and files when searching, comma separated
   --generalInfo value, -g value  Go file path in which 'swagger general API Info' is written (default: "main.go")
   --help, -h                     show help (default: false)
```

```
// GetStructArrayByString example
// @Description  get struct array by ID
// @ID           get-struct-array-by-string
// @Accept       json
// @Produce      json
// @Param        some_id  path      string        true   "Some ID"
// @Param        offset   query     int           true   "Offset"
// @Param        limit    query     int           true   "Offset"
// @Param        pet_id   query     int           false  "pet' id"
// @Param        book_id  query     int           false  "book' id"
// @Param        app_id   query     int           false  "app' id"
// @Param        x_key    query     string        false  "secret key"
// @Success      200      {string}  string        "ok"
// @Failure      400      {object}  web.APIError  "We need ID!!"
// @Failure      404      {object}  web.APIError  "Can not find ID"
// @Router       /testapi/get-struct-array-by-string/{some_id} [get]
```
### How it works

just like `go fmt`, It use `text/tabwriter` to format the comment. It scans the swag comments, especially '@param', '@success', '@Response', etc, recognize their boundaries, call `text/tabwriter` to format them. See the source code for more details.

**Relation issue**

**Additional context**

### CODE REVIEW

**Comment by ubogdan** [comment]
@HYY-yu This is pretty impressive PR and I feel it will be a nice feature for our community. Can you please fix the coverage so we may merge and include this in 1.7.5 version?

**Comment by HYY-yu** [comment]
It's very hard to improving coverage, I had to use [ the Monkey test.](https://bou.ke/blog/monkey-patching-in-go/)

**Review by ubogdan — DISMISSED** [review]
LGTM

**Comment by ubogdan** [comment]
I know the main focus on PR is the code. In the end, we are adding these features to improve the development experience.
Would you mind documenting this feature into README.md?

**Comment by HYY-yu** [comment]
Sure, I'll add to README later.

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@HYY-yu Thanks for your contribution.

**Pull request merged**
